/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelLineCmd.java
 *
 * Created on 25 oct. 2009, 15:46:30
 */

package manuserial;

/**
 *
 * @author thomas
 */
public class jPanelLineCmd extends javax.swing.JPanel {

    /** Creates new form jPanelLineCmd */
    public jPanelLineCmd() {
        initComponents();
    }
    
    public jPanelLineCmd(String txt) {
        initComponents();
        this.jTextFieldCmd.setText(txt);
    }

    private String stringToHexa(String str) {
        StringBuffer buf = new StringBuffer("");
        for (int i = 0; i < str.length(); i++) {
            int tmp = str.charAt(i);
            if (tmp < 16) {
                buf.append("0");
            }
            buf.append(Integer.toHexString(tmp).toUpperCase() + " ");
        }

        return buf.toString();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCmd = new javax.swing.JTextField();
        jButtonEnvoyer = new javax.swing.JButton();
        jButtonEffacer = new javax.swing.JButton();
        jCheckBoxEcho = new javax.swing.JCheckBox();
        jCheckBoxHexa = new javax.swing.JCheckBox();

        jTextFieldCmd.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldCmdInputMethodTextChanged(evt);
            }
        });
        jTextFieldCmd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCmdKeyTyped(evt);
            }
        });

        jButtonEnvoyer.setText("Envoyer");

        jButtonEffacer.setText("Effacer");
        jButtonEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEffacerActionPerformed(evt);
            }
        });

        jCheckBoxEcho.setText("echo");

        jCheckBoxHexa.setText("hex");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextFieldCmd, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxHexa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEcho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEffacer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnvoyer))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonEnvoyer)
                .addComponent(jButtonEffacer)
                .addComponent(jCheckBoxEcho)
                .addComponent(jCheckBoxHexa))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEffacerActionPerformed
        // TODO add your handling code here:
        this.jTextFieldCmd.setText("");
    }//GEN-LAST:event_jButtonEffacerActionPerformed

    private void jTextFieldCmdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCmdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCmdKeyTyped

    private void jTextFieldCmdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldCmdInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldCmdInputMethodTextChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEffacer;
    private javax.swing.JButton jButtonEnvoyer;
    private javax.swing.JCheckBox jCheckBoxEcho;
    private javax.swing.JCheckBox jCheckBoxHexa;
    private javax.swing.JTextField jTextFieldCmd;
    // End of variables declaration//GEN-END:variables

}
